# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitees', '0002_auto_20170712_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='choice',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4),
        ),
    ]
