# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSetting',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_fullname',
            new_name='username',
        ),
    ]
