# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, to='events.Schedule'),
        ),
    ]
