# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170323_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule_range',
            field=models.ManyToManyField(blank=True, to='events.Schedule', verbose_name='schedule_range'),
        ),
    ]
