# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='events.Schedule'),
        ),
    ]
