# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170317_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(default='test', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
