# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170318_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_allday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
